name = "PeterfalviProblem"
version = "0.1.0"
keywords = ["math"]
defaultTargets = ["PeterfalviProblem", "Solution"]

[leanOptions]
pp.unicode.fun = true # pretty-prints `fun a ↦ b`
autoImplicit = false
weak.linter.mathlibStandardSet = true

[[require]]
name = "mathlib"
scope = "leanprover-community"
rev = "v4.35.0-rc2"

[[lean_lib]]
name = "PeterfalviProblem"

[[lean_lib]]
name = "Challenge"

[[lean_lib]]
name = "Solution"
