/-
Copyright (c) 2026 Yawara Ishida. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Yawara Ishida
-/
import Mathlib.Algebra.CharP.Two
import Mathlib.LinearAlgebra.Matrix.Notation
import Mathlib.LinearAlgebra.Matrix.SpecialLinearGroup
import PeterfalviProblem.Basic.FrobeniusGroup

/-!
# The example `SL(2, 2^q)` for `p = 2`

Example 10 of Glauberman–Norton, due to Péterfalvi, shows that hypothesis (B) can hold. The same
example is Remark (II) in Appendix C of Bender–Glauberman. Take `p = 2`, any `q ≥ 1`, and
`G = SL(2, 2^q)`, with

* `σ(P) = {[[1, a], [0, 1]] : a ∈ 𝔽_{2^q}}`,
* `σ(U) = {[[a, 0], [0, a⁻¹]] : a ∈ 𝔽_{2^q}ˣ}`,
* `σ(P₀) = ⟨[[1, 1], [0, 1]]⟩`,
* `y = [[0, 1], [1, 1]]` and `Q = ⟨y⟩`.

For `p = 2` the norm is `x ↦ x^{2^q - 1}`, so `U` is all of `𝔽_{2^q}ˣ`, and `H` is the affine group
of the line over `𝔽_{2^q}`.

## Main results

* `sigmaSL2`: the injective homomorphism `σ : H → SL(2, 2^q)`.
* `map_primeLine_sigmaSL2_le_normalizer`: `σ(P₀)` normalizes `Q`.
* `map_primeLine_conj_sigmaSL2_le_normalizer`: `σ(P₀)^y = y⁻¹ σ(P₀) y` normalizes `σ(U)`. It is
  generated by the Weyl element `[[0, 1], [1, 0]]`.

`hypothesisB_two` in `PeterfalviProblem.Main` puts these together.

## Implementation notes

The book describes `σ(U)` as a set. The map `u ↦ [[u, 0], [0, u⁻¹]]` is not a homomorphism on
`H`, because conjugation by `[[v, 0], [0, v⁻¹]]` sends `[[1, a], [0, 1]]` to `[[1, v² a], [0, 1]]`,
while `u ∈ U` acts on `P` by `a ↦ u a`. In characteristic `2`, squaring is a bijection of
`𝔽_{2^q}ˣ`. So we use `u ↦ [[√u, 0], [0, √u⁻¹]]` with `√u = u^{2^{q-1}}`. Its image is the set in
the book.
-/

namespace PeterfalviProblem

open Matrix
open scoped Pointwise

/-! ## Normalizer helpers -/

/-- If conjugation by `x` and by `x⁻¹` both map `H` into itself, then `x` normalizes `H`. -/
theorem mem_normalizer_of_conj_mem {G : Type*} [Group G] {H : Subgroup G} {x : G}
    (h₁ : ∀ n ∈ H, x * n * x⁻¹ ∈ H) (h₂ : ∀ n ∈ H, x⁻¹ * n * x ∈ H) :
    x ∈ Subgroup.normalizer (H : Set G) := by
  rw [Subgroup.mem_normalizer_iff]
  intro n
  refine ⟨fun hn => h₁ n hn, fun hn => ?_⟩
  have := h₂ _ hn
  simpa [mul_assoc] using this

/-- If `x⁻¹ = x`, it is enough to check one inclusion. -/
theorem mem_normalizer_of_inv_self {G : Type*} [Group G] {H : Subgroup G} {x : G} (hx : x⁻¹ = x)
    (h : ∀ n ∈ H, x * n * x⁻¹ ∈ H) : x ∈ Subgroup.normalizer (H : Set G) := by
  refine mem_normalizer_of_conj_mem h fun n hn => ?_
  rw [hx]
  have := h n hn
  rwa [hx] at this

/-- If `x⁻¹ = x` and `x g x⁻¹ ∈ ⟨g⟩`, then `x` normalizes `⟨g⟩`. -/
theorem mem_normalizer_zpowers_of_inv_self {G : Type*} [Group G] {x g : G} (hx : x⁻¹ = x)
    (h : x * g * x⁻¹ ∈ Subgroup.zpowers g) :
    x ∈ Subgroup.normalizer ((Subgroup.zpowers g : Subgroup G) : Set G) := by
  refine mem_normalizer_of_inv_self hx ?_
  rintro n ⟨k, rfl⟩
  have hconj : x * g ^ k * x⁻¹ = (x * g * x⁻¹) ^ k := by
    simp
  rw [hconj]
  exact Subgroup.zpow_mem _ h k

/-! ## Triangular elements of `SL(2, F)` -/

namespace SL2

variable {F : Type*} [Field F]

/-- The matrix `[[1, a], [0, 1]]` as an element of `SL(2, F)`. -/
def upper (a : F) : SpecialLinearGroup (Fin 2) F := ⟨!![1, a; 0, 1], by simp⟩

/-- The matrix `[[u, 0], [0, u⁻¹]]` as an element of `SL(2, F)`. -/
def torus (u : Fˣ) : SpecialLinearGroup (Fin 2) F :=
  ⟨!![(u : F), 0; 0, ((u⁻¹ : Fˣ) : F)], by simp⟩

@[simp] theorem coe_upper (a : F) :
    (upper a : Matrix (Fin 2) (Fin 2) F) = !![1, a; 0, 1] := rfl

@[simp] theorem coe_torus (u : Fˣ) :
    (torus u : Matrix (Fin 2) (Fin 2) F) = !![(u : F), 0; 0, ((u⁻¹ : Fˣ) : F)] := rfl

theorem upper_mul_upper (a b : F) : upper a * upper b = upper (a + b) := by
  apply Subtype.ext
  rw [SpecialLinearGroup.coe_mul, coe_upper, coe_upper, coe_upper, Matrix.mul_fin_two]
  norm_num [add_comm]

theorem upper_zero : upper (0 : F) = 1 := by
  apply Subtype.ext
  rw [coe_upper, SpecialLinearGroup.coe_one, Matrix.one_fin_two]

/-- The additive group of `F`, embedded in `SL(2, F)` as the matrices `[[1, a], [0, 1]]`. This
is `σ` on `P`. -/
def upperHom : Multiplicative F →* SpecialLinearGroup (Fin 2) F where
  toFun a := upper a.toAdd
  map_one' := upper_zero
  map_mul' _ _ := (upper_mul_upper _ _).symm

@[simp] theorem upperHom_apply (a : Multiplicative F) : upperHom a = upper a.toAdd := rfl

theorem torus_mul_torus (u v : Fˣ) : torus u * torus v = torus (u * v) := by
  apply Subtype.ext
  rw [SpecialLinearGroup.coe_mul, coe_torus, coe_torus, coe_torus, Matrix.mul_fin_two]
  simp [Units.val_inv_eq_inv_val, mul_comm]

theorem torus_one : torus (1 : Fˣ) = 1 := by
  apply Subtype.ext
  rw [coe_torus, SpecialLinearGroup.coe_one, Matrix.one_fin_two]
  simp

/-- The diagonal matrices `[[u, 0], [0, u⁻¹]]` of `SL(2, F)`. Up to the square root explained in
the module docstring, this is `σ` on `U`. -/
def torusHom : Fˣ →* SpecialLinearGroup (Fin 2) F where
  toFun := torus
  map_one' := torus_one
  map_mul' u v := (torus_mul_torus u v).symm

@[simp] theorem torusHom_apply (u : Fˣ) : torusHom u = torus u := rfl

theorem torus_inv (u : Fˣ) : (torus u)⁻¹ = torus u⁻¹ := (map_inv torusHom u).symm

/-- Conjugating `[[1, a], [0, 1]]` by `[[u, 0], [0, u⁻¹]]` multiplies `a` by `u²`. -/
theorem torus_mul_upper_mul_torus_inv (u : Fˣ) (a : F) :
    torus u * upper a * (torus u)⁻¹ = upper ((u : F) * (u : F) * a) := by
  apply Subtype.ext
  rw [torus_inv, SpecialLinearGroup.coe_mul, SpecialLinearGroup.coe_mul, coe_torus, coe_upper,
    coe_torus, Matrix.mul_fin_two, Matrix.mul_fin_two, coe_upper]
  simp only [Units.val_inv_eq_inv_val, inv_inv, mul_zero, zero_mul, add_zero, zero_add, mul_one]
  rw [mul_inv_cancel₀ u.ne_zero, inv_mul_cancel₀ u.ne_zero,
    show (u : F) * a * (u : F) = (u : F) * (u : F) * a by ring]

/-- `[[1, a], [0, 1]] · [[u, 0], [0, u⁻¹]] = 1` only when `a = 0` and `u = 1`. This gives the
injectivity of `σ`. -/
theorem upper_mul_torus_eq_one_iff (a : F) (u : Fˣ) :
    upper a * torus u = 1 ↔ a = 0 ∧ u = 1 := by
  constructor
  · intro h
    have h' : (upper a * torus u : Matrix (Fin 2) (Fin 2) F) = 1 := by
      rw [← SpecialLinearGroup.coe_mul, h, SpecialLinearGroup.coe_one]
    rw [coe_upper, coe_torus, Matrix.mul_fin_two, Matrix.one_fin_two] at h'
    have h00 := congrFun (congrFun h' 0) 0
    have h01 := congrFun (congrFun h' 0) 1
    simp only [one_mul, mul_zero, add_zero, Units.val_inv_eq_inv_val, zero_add, zero_mul,
      Fin.isValue, of_apply, cons_val', cons_val_zero, cons_val_fin_one, Units.val_eq_one,
      cons_val_one, mul_eq_zero, inv_eq_zero, Units.ne_zero, or_false] at h00 h01
    exact ⟨h01, h00⟩
  · rintro ⟨rfl, rfl⟩
    rw [upper_zero, torus_one, one_mul]

section CharTwo

variable [CharP F 2]

/-- The element `y = [[0, 1], [1, 1]]`. It has order `3`. -/
def elemY : SpecialLinearGroup (Fin 2) F := ⟨!![0, 1; 1, 1], by simp [CharTwo.neg_eq]⟩

/-- The Weyl element `w = [[0, 1], [1, 0]]`. It inverts the diagonal matrices. -/
def elemW : SpecialLinearGroup (Fin 2) F := ⟨!![0, 1; 1, 0], by simp [CharTwo.neg_eq]⟩

@[simp] theorem coe_elemY :
    ((elemY : SpecialLinearGroup (Fin 2) F) : Matrix (Fin 2) (Fin 2) F) = !![0, 1; 1, 1] := rfl

@[simp] theorem coe_elemW :
    ((elemW : SpecialLinearGroup (Fin 2) F) : Matrix (Fin 2) (Fin 2) F) = !![0, 1; 1, 0] := rfl

theorem coe_elemY_sq :
    ((elemY (F := F) ^ 2 : SpecialLinearGroup (Fin 2) F) : Matrix (Fin 2) (Fin 2) F) =
      !![1, 1; 1, 0] := by
  rw [sq, SpecialLinearGroup.coe_mul, coe_elemY, Matrix.mul_fin_two]
  simp [CharTwo.add_self_eq_zero]

/-- `y³ = 1`. -/
theorem elemY_pow_three : (elemY (F := F)) ^ 3 = 1 := by
  apply Subtype.ext
  rw [show (3 : ℕ) = 2 + 1 from rfl, pow_succ, SpecialLinearGroup.coe_mul, coe_elemY_sq,
    coe_elemY, SpecialLinearGroup.coe_one, Matrix.mul_fin_two, Matrix.one_fin_two]
  simp [CharTwo.add_self_eq_zero]

theorem elemY_ne_one : (elemY (F := F)) ≠ 1 := by
  intro h
  have h' : (elemY (F := F) : Matrix (Fin 2) (Fin 2) F) = 1 := by
    rw [h, SpecialLinearGroup.coe_one]
  rw [coe_elemY, Matrix.one_fin_two] at h'
  have h00 := congrFun (congrFun h' 0) 0
  simp at h00

theorem orderOf_elemY : orderOf (elemY (F := F)) = 3 :=
  orderOf_eq_prime elemY_pow_three elemY_ne_one

theorem elemY_inv_eq_sq : (elemY (F := F))⁻¹ = elemY ^ 2 :=
  inv_eq_of_mul_eq_one_right (by rw [← pow_succ']; exact elemY_pow_three (F := F))

theorem elemW_mul_elemW : (elemW (F := F)) * elemW = 1 := by
  apply Subtype.ext
  rw [SpecialLinearGroup.coe_mul, coe_elemW, SpecialLinearGroup.coe_one, Matrix.mul_fin_two,
    Matrix.one_fin_two]
  norm_num

theorem elemW_inv : (elemW (F := F))⁻¹ = elemW :=
  inv_eq_of_mul_eq_one_right elemW_mul_elemW

theorem upper_one_mul_upper_one : upper (1 : F) * upper 1 = 1 := by
  rw [upper_mul_upper, CharTwo.add_self_eq_zero, upper_zero]

theorem upper_one_inv : (upper (1 : F))⁻¹ = upper 1 :=
  inv_eq_of_mul_eq_one_right upper_one_mul_upper_one

/-- `s y s⁻¹ = y²` for `s = [[1, 1], [0, 1]]`. -/
theorem upper_one_conj_elemY :
    upper (1 : F) * elemY * (upper (1 : F))⁻¹ = elemY ^ 2 := by
  apply Subtype.ext
  rw [upper_one_inv, SpecialLinearGroup.coe_mul, SpecialLinearGroup.coe_mul, coe_elemY_sq,
    coe_upper, coe_elemY, Matrix.mul_fin_two, Matrix.mul_fin_two]
  simp [CharTwo.add_self_eq_zero]

/-- `s = [[1, 1], [0, 1]]` normalizes `Q = ⟨y⟩`. -/
theorem upper_one_mem_normalizer_zpowers_elemY :
    upper (1 : F) ∈ Subgroup.normalizer
      ((Subgroup.zpowers (elemY (F := F))) : Set (SpecialLinearGroup (Fin 2) F)) := by
  refine mem_normalizer_zpowers_of_inv_self upper_one_inv ?_
  rw [upper_one_conj_elemY]
  exact Subgroup.pow_mem _ (Subgroup.mem_zpowers _) 2

/-- `y⁻¹ s y = w` for `s = [[1, 1], [0, 1]]`. So `σ(P₀)^y` is generated by the Weyl element. -/
theorem elemY_inv_conj_upper_one :
    (elemY (F := F))⁻¹ * upper (1 : F) * elemY = elemW := by
  apply Subtype.ext
  rw [elemY_inv_eq_sq, SpecialLinearGroup.coe_mul, SpecialLinearGroup.coe_mul, coe_elemY_sq,
    coe_upper, coe_elemY, coe_elemW, Matrix.mul_fin_two, Matrix.mul_fin_two]
  simp [CharTwo.add_self_eq_zero]

/-- `w [[u, 0], [0, u⁻¹]] w⁻¹ = [[u⁻¹, 0], [0, u]]`. -/
theorem elemW_conj_torus (u : Fˣ) :
    elemW * torus u * (elemW (F := F))⁻¹ = torus u⁻¹ := by
  apply Subtype.ext
  rw [elemW_inv, SpecialLinearGroup.coe_mul, SpecialLinearGroup.coe_mul, coe_elemW, coe_torus,
    coe_torus, Matrix.mul_fin_two, Matrix.mul_fin_two]
  norm_num [Units.val_inv_eq_inv_val]

end CharTwo

end SL2

/-! ## The homomorphism `σ : H → SL(2, 2^q)` -/

section Model

variable (q : ℕ)

/-- The square root `u ↦ u^{2^{q-1}}` on `𝔽_{2^q}ˣ`. It is the inverse of squaring, because
`u^{2^q} = u`. -/
noncomputable def sqrtHom : (GaloisField 2 q)ˣ →* (GaloisField 2 q)ˣ :=
  powMonoidHom (2 ^ (q - 1))

@[simp] theorem sqrtHom_apply (u : (GaloisField 2 q)ˣ) :
    sqrtHom q u = u ^ (2 ^ (q - 1)) := rfl

/-- `√u · √u = u`. -/
theorem sqrtHom_sq (hq : q ≠ 0) (u : (GaloisField 2 q)ˣ) :
    sqrtHom q u * sqrtHom q u = u := by
  have : Fintype (GaloisField 2 q) := Fintype.ofFinite _
  have hcard : Fintype.card (GaloisField 2 q) = 2 ^ q := by
    rw [← Nat.card_eq_fintype_card]
    exact GaloisField.card 2 q hq
  have hpow : (2 : ℕ) ^ (q - 1) * 2 = 2 ^ q := by
    rw [← pow_succ]
    congr 1
    omega
  refine Units.ext ?_
  rw [Units.val_mul, sqrtHom_apply, Units.val_pow_eq_pow_val, ← pow_add,
    show 2 ^ (q - 1) + 2 ^ (q - 1) = 2 ^ (q - 1) * 2 by ring, hpow, ← hcard]
  exact FiniteField.pow_card _

/-- `√u · √u = u`, for the field elements. -/
theorem sqrtHom_val_mul_val (hq : q ≠ 0) (u : (GaloisField 2 q)ˣ) :
    ((sqrtHom q u : (GaloisField 2 q)ˣ) : GaloisField 2 q) *
        ((sqrtHom q u : (GaloisField 2 q)ˣ) : GaloisField 2 q) =
      (u : GaloisField 2 q) := by
  rw [← Units.val_mul, sqrtHom_sq q hq]

/-- The condition that makes `σ` a homomorphism on `H = P ⋊ U`. -/
theorem sigmaSL2_compat (hq : q ≠ 0) (u : normOneUnits 2 q) :
    (SL2.upperHom : Multiplicative (GaloisField 2 q) →* _).comp
        ((normOneMulAction 2 q u).toMonoidHom) =
      (MulAut.conj
          ((SL2.torusHom.comp
            ((sqrtHom q).comp (normOneUnits 2 q).subtype)) u)).toMonoidHom.comp
        SL2.upperHom := by
  refine MonoidHom.ext fun a => ?_
  have hsq := sqrtHom_val_mul_val q hq (u : (GaloisField 2 q)ˣ)
  have hact : ((normOneMulAction 2 q u) a).toAdd =
      ((u : (GaloisField 2 q)ˣ) : GaloisField 2 q) * a.toAdd :=
    normOneMulAction_apply 2 q u a.toAdd
  simp only [MonoidHom.coe_comp, Function.comp_apply, MulEquiv.coe_toMonoidHom,
    MulAut.conj_apply, SL2.upperHom_apply, SL2.torusHom_apply, Subgroup.coe_subtype]
  rw [SL2.torus_mul_upper_mul_torus_inv, hsq, hact]

/-- **The homomorphism `σ : H → SL(2, 2^q)`.** It sends `a ∈ P` to `[[1, a], [0, 1]]` and
`u ∈ U` to `[[√u, 0], [0, √u⁻¹]]`. The image of `U` is the group of all diagonal matrices. -/
noncomputable def sigmaSL2 (hq : q ≠ 0) :
    normOneFrobeniusGroup 2 q →* SpecialLinearGroup (Fin 2) (GaloisField 2 q) :=
  SemidirectProduct.lift SL2.upperHom
    (SL2.torusHom.comp ((sqrtHom q).comp (normOneUnits 2 q).subtype))
    (sigmaSL2_compat q hq)

@[simp] theorem sigmaSL2_inl (hq : q ≠ 0) (a : GaloisField 2 q) :
    sigmaSL2 q hq (SemidirectProduct.inl (Multiplicative.ofAdd a)) = SL2.upper a :=
  SemidirectProduct.lift_inl _ _ _ _

@[simp] theorem sigmaSL2_inr (hq : q ≠ 0) (u : normOneUnits 2 q) :
    sigmaSL2 q hq (SemidirectProduct.inr u) =
      SL2.torus (sqrtHom q (u : (GaloisField 2 q)ˣ)) :=
  SemidirectProduct.lift_inr _ _ _ _

theorem sigmaSL2_apply (hq : q ≠ 0) (g : normOneFrobeniusGroup 2 q) :
    sigmaSL2 q hq g =
      SL2.upper g.left.toAdd * SL2.torus (sqrtHom q (g.right : (GaloisField 2 q)ˣ)) := rfl

theorem sigmaSL2_injective (hq : q ≠ 0) : Function.Injective (sigmaSL2 q hq) := by
  rw [injective_iff_map_eq_one]
  intro g hg
  rw [sigmaSL2_apply] at hg
  obtain ⟨ha, hu⟩ := (SL2.upper_mul_torus_eq_one_iff _ _).mp hg
  have hright : g.right = 1 := by
    refine Subtype.ext (Units.ext ?_)
    have hval := sqrtHom_val_mul_val q hq (g.right : (GaloisField 2 q)ˣ)
    rw [hu] at hval
    simpa using hval.symm
  have hleft : g.left = 1 := by
    refine Multiplicative.toAdd.injective ?_
    simpa using ha
  exact SemidirectProduct.ext hleft hright

/-- For `p = 2` the prime field is `𝔽₂ = {0, 1}`, so `P₀ = {1, x}` with `x = inl 1`. -/
theorem mem_primeLine_two {g : normOneFrobeniusGroup 2 q} (hg : g ∈ primeLine 2 q) :
    g = 1 ∨ g = primeLineGenerator 2 q := by
  obtain ⟨z, hz, rfl⟩ := hg
  obtain ⟨c, hc⟩ : ∃ c : ZMod 2, algebraMap (ZMod 2) (GaloisField 2 q) c = z.toAdd := by
    simpa using hz
  have hc2 : ∀ d : ZMod 2, d = 0 ∨ d = 1 := by decide
  rcases hc2 c with rfl | rfl
  · left
    rw [show z = 1 by rw [← ofAdd_toAdd z, ← hc, map_zero, ofAdd_zero], map_one]
  · right
    rw [show z = Multiplicative.ofAdd 1 by rw [← ofAdd_toAdd z, ← hc, map_one]]
    rfl

end Model

/-! ## Hypothesis (B) for `p = 2` -/

/-- The Weyl element normalizes `σ(U)`. -/
theorem elemW_mem_normalizer_complement (q : ℕ) (hq : q ≠ 0) :
    SL2.elemW ∈ Subgroup.normalizer
      (((normOneFrobeniusComplement 2 q).map (sigmaSL2 q hq) :
          Subgroup (SpecialLinearGroup (Fin 2) (GaloisField 2 q))) :
        Set (SpecialLinearGroup (Fin 2) (GaloisField 2 q))) := by
  refine mem_normalizer_of_inv_self SL2.elemW_inv ?_
  rintro n ⟨g, hg, rfl⟩
  rw [normOneFrobeniusComplement] at hg
  obtain ⟨u, rfl⟩ := hg
  refine ⟨SemidirectProduct.inr u⁻¹, ⟨u⁻¹, rfl⟩, ?_⟩
  rw [sigmaSL2_inr, sigmaSL2_inr, SL2.elemW_conj_torus, Subgroup.coe_inv, map_inv]

/-- `σ(P₀) = ⟨[[1, 1], [0, 1]]⟩` normalizes `Q = ⟨y⟩`. -/
theorem map_primeLine_sigmaSL2_le_normalizer (q : ℕ) (hq : q ≠ 0) :
    (primeLine 2 q).map (sigmaSL2 q hq) ≤ Subgroup.normalizer
      ((Subgroup.zpowers (SL2.elemY (F := GaloisField 2 q))) :
        Set (SpecialLinearGroup (Fin 2) (GaloisField 2 q))) := by
  rintro x ⟨g, hg, rfl⟩
  rcases mem_primeLine_two q hg with rfl | rfl
  · rw [map_one]
    exact Subgroup.one_mem _
  · rw [primeLineGenerator, sigmaSL2_inl]
    exact SL2.upper_one_mem_normalizer_zpowers_elemY

/-- `σ(P₀)^y = y⁻¹ σ(P₀) y` normalizes `σ(U)`: it is generated by the Weyl element. -/
theorem map_primeLine_conj_sigmaSL2_le_normalizer (q : ℕ) (hq : q ≠ 0) :
    (primeLine 2 q).map
        ((MulAut.conj (SL2.elemY (F := GaloisField 2 q))⁻¹).toMonoidHom.comp (sigmaSL2 q hq)) ≤
      Subgroup.normalizer
        (((normOneFrobeniusComplement 2 q).map (sigmaSL2 q hq) :
            Subgroup (SpecialLinearGroup (Fin 2) (GaloisField 2 q))) :
          Set (SpecialLinearGroup (Fin 2) (GaloisField 2 q))) := by
  rintro x ⟨g, hg, rfl⟩
  rcases mem_primeLine_two q hg with rfl | rfl
  · rw [map_one]
    exact Subgroup.one_mem _
  · rw [MonoidHom.comp_apply, primeLineGenerator, sigmaSL2_inl, MulEquiv.coe_toMonoidHom,
      MulAut.conj_apply, inv_inv, SL2.elemY_inv_conj_upper_one]
    exact elemW_mem_normalizer_complement q hq

/-- The subgroup `Q = ⟨y⟩` has order `3`, which is prime to `p = 2`. -/
theorem not_two_dvd_card_zpowers_elemY (q : ℕ) :
    ¬ 2 ∣ Nat.card (Subgroup.zpowers (SL2.elemY (F := GaloisField 2 q))) := by
  rw [Nat.card_zpowers, SL2.orderOf_elemY]
  decide

end PeterfalviProblem
