/-
Copyright (c) 2026 Yawara Ishida. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Yawara Ishida
-/
import PeterfalviProblem.Basic.FrobeniusGroup

/-!
# BG Appendix C, Lemma C.3: the transported configuration

H. Bender and G. Glauberman, *Local Analysis for the Odd Order Theorem*
(LMS LNS 188, 1994), Appendix C, §3 (pp. 148--152).

Under hypothesis (B) the monomorphism `σ : H = P ⋊ U → G` transports the concrete Frobenius
group into `G`.  This file develops the resulting configuration inside `G`: the distinguished
element `s = σ(1) ∈ σ(P₀)`, the isomorphism `U ≅ σ(U)`, the decomposition `σ(H) = PU` with
`P ∩ U = 1`, the fact that `P` is characteristic in `PU` (`p`-torsion lands in `P`), the
irreducibility bridge for subgroups between `U` and `PU`, and Steps 1--2 of Lemma C.3 read
through `σ`.  It culminates in `s_not_normalizes_U`, the contradiction that drives Step 4.

Everything here is stated against the book's abstract hypotheses
(`PeterfalviProblem.FieldNormalizerData` = (A) + (B)); nothing refers to the Peterfalvi Section 16
configuration, which supplies one instance of (B) along the Feit--Thompson spine (issue 0151).
-/

namespace PeterfalviProblem

open scoped Pointwise

/-! ## The Step 4 output interface

Lemma C.3 Step 4 produces a norm relation on the norm set `E`.  The book states it in three
equivalent shapes -- a twisted-inverse step over field elements, the same over units, and the
resulting relation `N(2a − 1) = 1` -- and BG's final odd-iterate argument only needs the
narrowest one, on the norm-one group `U`.  These are the obligations the transported
configuration below discharges. -/

/-! ## The transported configuration -/

variable {p q : ℕ} [Fact p.Prime] {G : Type*} [Group G]

namespace FieldNormalizerData

/-- The BG element `s ∈ P₀#`, transported to `G` through the concrete
field-normalizer monomorphism. -/
noncomputable def s (data : FieldNormalizerData p q G) : G :=
  data.sigma (primeLineGenerator p q)

/-- The transported element `s` lies in Peterfalvi's subgroup `W₂ = σ(P₀)`. -/
theorem s_mem_W2 (data : FieldNormalizerData p q G) :
    data.s ∈ data.W2 := by
  rw [← data.sigma_P0_eq_W2]
  exact ⟨primeLineGenerator p q,
    primeLineGenerator_mem p q, rfl⟩

/-- The transported element `s` lies in the transported additive kernel `P`. -/
theorem s_mem_P (data : FieldNormalizerData p q G) :
    data.s ∈ data.P := by
  rw [← data.sigma_P_eq_P]
  refine ⟨primeLineGenerator p q, ?_, rfl⟩
  dsimp [primeLineGenerator, normOneFrobeniusKernel]
  exact ⟨Multiplicative.ofAdd (1 : GaloisField p q), rfl⟩

/-- The image of the concrete Frobenius group is the subgroup generated by the
transported additive kernel `P` and complement `U`. -/
theorem P_sup_U_eq_sigma_top (data : FieldNormalizerData p q G) :
    data.P ⊔ data.U =
      (⊤ : Subgroup (normOneFrobeniusGroup p q)).map data.sigma := by
  calc
    data.P ⊔ data.U =
        (normOneFrobeniusKernel p q).map data.sigma ⊔
          (normOneFrobeniusComplement p q).map data.sigma := by
      rw [data.sigma_P_eq_P, data.sigma_U_eq_U]
    _ = (normOneFrobeniusKernel p q ⊔
          normOneFrobeniusComplement p q).map data.sigma := by
      rw [Subgroup.map_sup]
    _ = (⊤ : Subgroup (normOneFrobeniusGroup p q)).map data.sigma := by
      rw [normOneFrobeniusKernel_sup_complement_eq_top p q]

/-- Transported form: every element of Peterfalvi's `P` has `p`-th power `1`. -/
theorem P_pow_p_eq_one (data : FieldNormalizerData p q G)
    {x : G} (hx : x ∈ data.P) :
    x ^ p = 1 := by
  rw [← data.sigma_P_eq_P] at hx
  rcases hx with ⟨h, hhK, hh⟩
  have hhpow := normOneFrobeniusKernel_pow_p_eq_one p q hhK
  calc
    x ^ p = (data.sigma h) ^ p := by rw [hh]
    _ = data.sigma (h ^ p) := by rw [map_pow]
    _ = 1 := by rw [hhpow, map_one]

/-- Transported form of `P char PU`: the `p`-torsion in `PU` lies in `P`. -/
theorem mem_P_of_mem_P_sup_U_of_pow_p_eq_one
    (data : FieldNormalizerData p q G)
    {x : G} (hxPU : x ∈ data.P ⊔ data.U) (hxp : x ^ p = 1) :
    x ∈ data.P := by
  have hxrange : x ∈ (⊤ : Subgroup (normOneFrobeniusGroup p q)).map data.sigma := by
    rwa [← data.P_sup_U_eq_sigma_top]
  rcases hxrange with ⟨h, _hhtop, hh⟩
  have hhp : h ^ p = 1 := data.sigma_injective (by
    calc
      data.sigma (h ^ p) = (data.sigma h) ^ p := by rw [map_pow]
      _ = x ^ p := by rw [hh]
      _ = 1 := hxp
      _ = data.sigma 1 := by rw [map_one])
  have hhK := normOneFrobeniusGroup_mem_kernel_of_pow_p_eq_one p q data.q_prime.ne_zero h hhp
  rw [← data.sigma_P_eq_P]
  exact ⟨h, hhK, hh⟩

/-- BG Appendix C Step 3, `P char PU` in normalizer form: anything normalizing
`PU` also normalizes its additive kernel `P`. -/
theorem normalizer_P_sup_U_le_normalizer_P
    (data : FieldNormalizerData p q G) :
    Subgroup.normalizer ((data.P ⊔ data.U : Subgroup G) : Set G) ≤
      Subgroup.normalizer (data.P : Set G) := by
  intro g hg
  rw [Subgroup.mem_normalizer_iff] at hg ⊢
  intro x
  constructor
  · intro hxP
    have hxPU : x ∈ data.P ⊔ data.U := (le_sup_left : data.P ≤
      data.P ⊔ data.U) hxP
    have hconjPU : g * x * g⁻¹ ∈ data.P ⊔ data.U := (hg x).mp hxPU
    have hxpow : x ^ p = 1 := data.P_pow_p_eq_one hxP
    have hconjpow : (g * x * g⁻¹) ^ p = 1 := by
      have h := congrArg (MulAut.conj g) hxpow
      rw [map_pow] at h
      simpa [MulAut.conj_apply] using h
    exact data.mem_P_of_mem_P_sup_U_of_pow_p_eq_one hconjPU hconjpow
  · intro hxconjP
    have hconjPU : g * x * g⁻¹ ∈ data.P ⊔ data.U :=
      (le_sup_left : data.P ≤ data.P ⊔ data.U) hxconjP
    have hxPU : x ∈ data.P ⊔ data.U := (hg x).mpr hconjPU
    have hconjpow : (g * x * g⁻¹) ^ p = 1 := data.P_pow_p_eq_one hxconjP
    have hxpow : x ^ p = 1 := by
      have h := congrArg (MulAut.conj g⁻¹) hconjpow
      rw [map_pow] at h
      have hback : MulAut.conj g⁻¹ (g * x * g⁻¹) = x := by
        simp
        group
      rw [hback] at h
      simpa [MulAut.conj_apply] using h
    exact data.mem_P_of_mem_P_sup_U_of_pow_p_eq_one hxPU hxpow

/-- BG Appendix C, Lemma C.3 Step 2 inside concrete `P⋊U`: if
`s₁ u s₂` lies in the complement, then either both prime-line factors are
trivial or the complement factor is trivial and the prime-line factors cancel. -/
theorem generatorRelation_step2_primeLine (data : FieldNormalizerData p q G) {c d : ZMod p}
    (u : normOneUnits p q)
    (hmem : (primeLineElement p q c *
        (SemidirectProduct.inr u : normOneFrobeniusGroup p q) *
          primeLineElement p q d) ∈ normOneFrobeniusComplement p q) :
    (c = 0 ∧ d = 0) ∨ (u = 1 ∧ c + d = 0) := by
  have hmem_original :
      ((SemidirectProduct.inl
          (Multiplicative.ofAdd
            ((algebraMap (ZMod p) (GaloisField p q) c) *
              (1 : GaloisField p q))) : normOneFrobeniusGroup p q) *
        SemidirectProduct.inr u *
          SemidirectProduct.inl
            (Multiplicative.ofAdd
              ((algebraMap (ZMod p) (GaloisField p q) d) *
                (1 : GaloisField p q)))) ∈
        (SemidirectProduct.inr : normOneUnits p q →*
          normOneFrobeniusGroup p q).range := by
    simpa [primeLineElement, normOneFrobeniusComplement,
      normOneFrobeniusComplement] using hmem
  exact
    normOneFrobenius_generatorRelation_step2_primeLine
      (p := p) (q := q) data.q_prime data.cyclotomic_coprime
      (s := (1 : GaloisField p q)) one_ne_zero
      (c := c) (d := d) u hmem_original

/-- BG Appendix C, Lemma C.3 Step 2 transported to `G`: the same alternative can
be read from membership of the transported product in `U`. -/
theorem generatorRelation_step2_primeLine_of_sigma_mem_U
    (data : FieldNormalizerData p q G)
    {c d : ZMod p} (u : normOneUnits p q)
    (hmem : data.sigma (primeLineElement p q c) *
        data.sigma (SemidirectProduct.inr u : normOneFrobeniusGroup p q) *
          data.sigma (primeLineElement p q d) ∈ data.U) :
    (c = 0 ∧ d = 0) ∨ (u = 1 ∧ c + d = 0) := by
  have hmem_map : data.sigma (primeLineElement p q c) *
        data.sigma (SemidirectProduct.inr u : normOneFrobeniusGroup p q) *
          data.sigma (primeLineElement p q d) ∈
      (normOneFrobeniusComplement p q).map data.sigma := by
    rwa [data.sigma_U_eq_U]
  rcases hmem_map with ⟨g, hgU, hg⟩
  let prodH : normOneFrobeniusGroup p q :=
    primeLineElement p q c *
      (SemidirectProduct.inr u : normOneFrobeniusGroup p q) *
        primeLineElement p q d
  have hprod_sigma : data.sigma prodH =
      data.sigma (primeLineElement p q c) *
        data.sigma (SemidirectProduct.inr u : normOneFrobeniusGroup p q) *
          data.sigma (primeLineElement p q d) := by
    simp [prodH, map_mul]
  have hg_eq : g = prodH := data.sigma_injective (by
    rw [hg, hprod_sigma])
  have hmemH : prodH ∈ normOneFrobeniusComplement p q := by
    simpa [← hg_eq] using hgU
  exact data.generatorRelation_step2_primeLine u hmemH

/-- The chosen nonidentity element `s ∈ P₀` cannot normalize `U`.  Otherwise a
nontrivial norm-one unit `u` would give `s u s⁻¹ ∈ U`, and BG Appendix C,
Lemma C.3 Step 2 forces `u = 1`. -/
theorem s_not_normalizes_U (data : FieldNormalizerData p q G) :
    data.s ∉ Subgroup.normalizer (data.U : Set G) := by
  intro hsN
  rcases exists_normOneUnit_ne_one p q data.q_prime.one_lt with ⟨u, hu_ne⟩
  have huU :
      data.sigma (SemidirectProduct.inr u : normOneFrobeniusGroup p q) ∈
        data.U := by
    rw [← data.sigma_U_eq_U]
    exact ⟨SemidirectProduct.inr u, ⟨u, rfl⟩, rfl⟩
  have hconjU :
      data.s *
          data.sigma (SemidirectProduct.inr u : normOneFrobeniusGroup p q) *
            data.s⁻¹ ∈ data.U :=
    (Subgroup.mem_normalizer_iff.mp hsN
      (data.sigma (SemidirectProduct.inr u : normOneFrobeniusGroup p q))).mp huU
  have hsigma_inv :
      data.sigma (primeLineElement p q (-1)) = data.s⁻¹ := by
    rw [primeLineElement_neg p q (1 : ZMod p)]
    simp [s, primeLineElement_one]
  have hmem_step :
      data.sigma (primeLineElement p q 1) *
          data.sigma (SemidirectProduct.inr u : normOneFrobeniusGroup p q) *
            data.sigma (primeLineElement p q (-1)) ∈ data.U := by
    simpa [s, primeLineElement_one, hsigma_inv] using hconjU
  have hstep :=
    data.generatorRelation_step2_primeLine_of_sigma_mem_U
      (c := (1 : ZMod p)) (d := (-1 : ZMod p)) u hmem_step
  rcases hstep with hzero | hone
  · have h1_ne_zero : (1 : ZMod p) ≠ 0 := one_ne_zero
    exact h1_ne_zero hzero.1
  · exact hu_ne hone.1

end FieldNormalizerData

end PeterfalviProblem
