/-
Copyright (c) 2026 Yawara Ishida. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Yawara Ishida
-/
import PeterfalviProblem.Proof.FieldLayers

/-!
# BG Appendix C, Problem 1: the trace obstruction

`PeterfalviProblem.false_of_collisionSet_spanning` refutes hypothesis (B) once the
`S`-values of *all* collisions span `𝔽_{3^q}` over the prime field.  This file replaces that
spanning hypothesis by a **single collision**:

> if one collision has `Tr(S) ≠ 0`, hypothesis (B) has no witness.

The mechanism is that the collision data is *Frobenius-equivariant*.  A collision is a pair
`p, r` of elements of the Paley set with `p^E - (p-1)^E = r^E - (r-1)^E`; in characteristic three
`p ↦ p³` is a ring endomorphism and `p³ - 1 = (p-1)³`, so cubing a collision is again a collision
and its `S`-value is cubed:

`S(p³, r³) = S(p, r)³`.

Relation (4) of `notes/bg/appC_problem1_partial_resolution.md` says `b(S)^{a(-1)} = b(S')`, i.e.
`x · b(S) · x⁻¹ = b(S')`.  Applying it to the `q` Frobenius conjugates of one collision and
multiplying the resulting relations inside the abelian second layer gives

`x · b(Tr S) · x⁻¹ = b(Tr S')`,     `Tr S = ∑_{j<q} S^{3^j}`.

Both traces lie in the prime field `𝔽₃`, so `b(Tr S)` and `b(Tr S')` lie in the group of order
three generated by `w = b(1) = x^g`.  Conjugation by `x` therefore acts on `⟨w⟩ ≅ C₃` through
`Aut(C₃) ≅ C₂`, and `x³ = 1`, so it acts trivially: `x` centralises `x^g`.  That is exactly the
configuration refuted by `not_commute_conj` (Theorem 1's endgame).

Compared with `false_of_collisionSet_spanning` the criterion here is strictly weaker in its
hypotheses — one collision instead of a spanning family — and it does not need the exponent to be
non-Frobenius (`hnotfrob`), because the contradiction no longer runs through the perfectness of
`N`.  It is the criterion verified computationally in `notes/meta/gap/verify_trace_obstruction.g`.

## Main results

* `CollisionPair` — the collision data of relation (4), keeping *both* `S` and `S'`.
* `exists_collisionPair_of_sub_ne_zero` — the square-difference requirement is free: of the two
  orderings of a collision exactly one has square `δ`, since `-1` is a non-square.
* `CollisionPair.frobenius` — cubing a collision cubes its `S`-values.
* `conj_layerFieldHom_one_eq` — relation (4) as an equation.
* `fieldTrace_pow_char` — `Tr S` lies in the prime field.
* `false_of_collisionPair_trace_ne_zero` — **the trace obstruction**.
* `false_of_collisionPair_trace` — its final form: one collision suffices unless *both* traces
  vanish.
-/

namespace PeterfalviProblem

open Finset

section PrimeField

variable {p q : ℕ} [Fact p.Prime]

end PrimeField

section Aut

variable {G : Type*} [Group G]

end Aut

section GroupSide

variable {p q : ℕ} [Fact p.Prime] {G : Type*} [Group G]

/-! ### The collision data, keeping both endpoints

`collisionSet` records only the `S`-value that gets conjugated; the trace obstruction needs the
*pair* `(S, S')` of relation (4), because the Frobenius moves both. -/

/-- **A collision of the map `p ↦ p^E - (p-1)^E` on the Paley set, with square difference.**
`p₀ = p₁ + 1` and `r₀ = r₁ + 1` are the two Paley pairs, `d₀` is the (norm-one, i.e. square)
difference `δ = r₀^e - p₀^e`, and `S`, `S'` are the two normalised third-layer values.  Relation
(4) reads `x · b(S) · x⁻¹ = b(S')` (`conj_layerFieldHom_one_eq`). -/
def CollisionPair (p q e : ℕ) [Fact p.Prime] (S S' : GaloisField p q) : Prop :=
  ∃ p₀ p₁ r₀ r₁ d₀ : normOneUnits p q,
    normOneVal p₀ = normOneVal p₁ + 1 ∧ normOneVal r₀ = normOneVal r₁ + 1 ∧
    normOneVal p₀ ^ e - normOneVal p₁ ^ e = normOneVal r₀ ^ e - normOneVal r₁ ^ e ∧
    normOneVal d₀ = normOneVal r₀ ^ e - normOneVal p₀ ^ e ∧
    S = (normOneVal p₁ ^ (e * e) - normOneVal p₀ ^ (e * e)) *
        normOneVal (d₀⁻¹ ^ (e * e)) ^ (e * e) ∧
    S' = (normOneVal r₁ ^ (e * e) - normOneVal r₀ ^ (e * e)) *
        normOneVal (d₀⁻¹ ^ (e * e)) ^ (e * e)

/-- **The square-difference requirement in `CollisionPair` costs nothing.**

`CollisionPair` asks for the difference `δ = r₀^e - p₀^e` of an *ordered* pair to be norm-one,
i.e. (for `p = 3`) a square.  Since `q` is odd, `-1` is a non-square in `𝔽_{3^q}`, so `δ` and `-δ`
are never both squares and never both non-squares: **exactly one of the two orderings of a
collision has square difference**.  Swapping the two Paley points therefore always produces a
`CollisionPair`, and the only genuine hypothesis left is that the collision be nondegenerate,
`δ ≠ 0` — which for a collision of distinct Paley points is automatic.

Consequences.  (i) Hypothesis (B1) of `notes/bg/appC_problem1_partial_resolution.md` — "some
collision with square difference exists" — collapses to the plain statement "some collision
exists".  (ii) The measured "only about half of the collisions are usable" (the enumeration for
`q = 7, 13`) is an artefact of a fixed ordering convention, not a real filter: *every* collision
is usable, so a certificate search may keep both orderings and doubles its hit rate. -/
theorem exists_collisionPair_of_sub_ne_zero (hp : p = 3) (hq : q ≠ 0) (hqodd : Odd q) {e : ℕ}
    (p₀ p₁ r₀ r₁ : normOneUnits p q)
    (hpp : normOneVal p₀ = normOneVal p₁ + 1) (hrr : normOneVal r₀ = normOneVal r₁ + 1)
    (hcoll : normOneVal p₀ ^ e - normOneVal p₁ ^ e = normOneVal r₀ ^ e - normOneVal r₁ ^ e)
    (hd : normOneVal r₀ ^ e - normOneVal p₀ ^ e ≠ 0) :
    ∃ S S', CollisionPair p q e S S' := by
  subst hp
  let : Fintype (GaloisField 3 q) := Fintype.ofFinite _
  have : CharP (GaloisField 3 q) 3 := by
    rw [← Algebra.charP_iff (ZMod 3) (GaloisField 3 q) 3]
    exact ZMod.charP 3
  have hcard : Fintype.card (GaloisField 3 q) = 3 ^ q := by
    rw [← Nat.card_eq_fintype_card]
    exact GaloisField.card 3 q hq
  have hchar2 : ringChar (GaloisField 3 q) ≠ 2 := by
    rw [ringChar.eq (GaloisField 3 q) 3]
    norm_num
  have h4 : Fintype.card (GaloisField 3 q) % 4 = 3 := by
    rw [hcard]
    have hq2 : q % 2 = 1 := Nat.odd_iff.mp hqodd
    have hk : q = 2 * (q / 2) + 1 := by omega
    rw [hk, pow_succ, pow_mul, Nat.mul_mod, Nat.pow_mod]
    norm_num
  rcases Paley.isSquare_or_isSquare_neg hchar2 h4 hd with hsq | hnsq
  · -- the given ordering already has square difference
    refine ⟨_, _, p₀, p₁, r₀, r₁,
      ⟨Units.mk0 _ hd, (mem_normOneUnits_iff_isSquare rfl hq _).mpr hsq⟩,
      hpp, hrr, hcoll, rfl, rfl, rfl⟩
  · -- swap the two Paley points; the difference changes sign, hence square class
    have hd' : normOneVal p₀ ^ e - normOneVal r₀ ^ e ≠ 0 := by
      intro h
      exact hd (by linear_combination -h)
    have hsq' : IsSquare (normOneVal p₀ ^ e - normOneVal r₀ ^ e) := by
      have hrw : normOneVal p₀ ^ e - normOneVal r₀ ^ e
          = -(normOneVal r₀ ^ e - normOneVal p₀ ^ e) := by ring
      rw [hrw]
      exact hnsq
    refine ⟨_, _, r₀, r₁, p₀, p₁,
      ⟨Units.mk0 _ hd', (mem_normOneUnits_iff_isSquare rfl hq _).mpr hsq'⟩,
      hrr, hpp, hcoll.symm, rfl, rfl, rfl⟩

/-- **The collision data is Frobenius-equivariant.**  In characteristic `p` the map `a ↦ a^p` is a
ring endomorphism fixing `1`, so it carries a Paley pair to a Paley pair, a collision to a
collision and the difference `δ` to `δ^p`; the two normalised values are raised to the `p`-th
power. -/
theorem CollisionPair.frobenius {e : ℕ} {S S' : GaloisField p q}
    (h : CollisionPair p q e S S') : CollisionPair p q e (S ^ p) (S' ^ p) := by
  obtain ⟨p₀, p₁, r₀, r₁, d₀, hpp, hrr, hcoll, hd, rfl, rfl⟩ := h
  have hswap : ∀ (a : GaloisField p q) (k : ℕ), (a ^ p) ^ k = (a ^ k) ^ p := by
    intro a k
    rw [← pow_mul, Nat.mul_comm, pow_mul]
  have hd0 : ((d₀ ^ p)⁻¹ : normOneUnits p q) ^ (e * e) = (d₀⁻¹ ^ (e * e)) ^ p := by
    rw [← inv_pow, ← pow_mul, ← pow_mul, Nat.mul_comm p (e * e)]
  refine ⟨p₀ ^ p, p₁ ^ p, r₀ ^ p, r₁ ^ p, d₀ ^ p, ?_, ?_, ?_, ?_, ?_, ?_⟩
  · simp only [normOneVal_pow]
    rw [hpp, add_pow_char, one_pow]
  · simp only [normOneVal_pow]
    rw [hrr, add_pow_char, one_pow]
  · simp only [normOneVal_pow, hswap, ← sub_pow_char, hcoll]
  · simp only [normOneVal_pow, hswap, ← sub_pow_char]
    rw [hd]
  · rw [hd0]
    simp only [normOneVal_pow, hswap, ← sub_pow_char, ← mul_pow]
  · rw [hd0]
    simp only [normOneVal_pow, hswap, ← sub_pow_char, ← mul_pow]

/-- Iterating `CollisionPair.frobenius`. -/
theorem CollisionPair.frobenius_iterate {e : ℕ} {S S' : GaloisField p q}
    (h : CollisionPair p q e S S') (j : ℕ) :
    CollisionPair p q e (S ^ p ^ j) (S' ^ p ^ j) := by
  induction j with
  | zero => simpa using h
  | succ k ih =>
      have hstep := ih.frobenius
      rwa [← pow_mul, ← pow_mul, ← pow_succ] at hstep

end GroupSide

end PeterfalviProblem
